- stat:
    path: ~/bin/pgfutter
  register: st

- name: Download pgfutter
  get_url:
    url: https://github.com/lukasmartinelli/pgfutter/releases/download/v1.1/pgfutter_linux_amd64
    dest: ~/bin/pgfutter
    mode: 0700
  when: not st.stat.exists

