- name: Update apt repos with latest virtualbox repo
  become: yes
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present
    update_cache: yes

- name: Add Oracle's apt-key so that packet downloaded from virtualbox repo is trusted
  become: yes
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Install virtualbox
  become: yes
  apt:
    name: virtualbox-5.1
    state: latest      

#- name: Install vagrant
#  become: yes
#  shell: git config --global user.email "douglasulian@hotmail.com" 
