---
- name: Ensure Pip is installed.
  become: yes
  package: 
    name: python-pip
    state: present

- name: Ensure pip_install_packages are installed.
  become: yes
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pip_install_packages }}"
