- name: Update apt repos with PostgreSQL repo
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present
    filename: 'pgdg.list'
    update_cache: yes

- name: Add PostgreSQL apt-key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Install PostgreSQL Client
  become: yes
  apt:
    name: postgresql-client-9.6
    state: latest
